"""add video_renders, onboarding_videos, outreach_videos tables

Revision ID: 014d3d636535
Revises: 186a8ad11c38
Create Date: 2026-05-03 21:19:40.222749

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '014d3d636535'
down_revision = '186a8ad11c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_renders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('programme', sa.String(length=20), nullable=False),
    sa.Column('video_style', sa.String(length=20), server_default='avatar', nullable=False),
    sa.Column('aspect_ratio', sa.String(length=5), server_default='16:9', nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('illustration_prompts', sa.JSON(), nullable=True),
    sa.Column('dalle_frame_urls', sa.JSON(), nullable=True),
    sa.Column('heygen_job_id', sa.String(length=128), nullable=True, unique=True),
    sa.Column('heygen_render_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('render_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_renders', schema=None) as batch_op:
        batch_op.create_index('idx_video_renders_account_programme_status', ['account_id', 'programme', 'status'], unique=False)

    op.create_table('onboarding_videos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('video_render_id', sa.String(length=64), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=128), nullable=False),
    sa.Column('recipient_company', sa.String(length=128), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_render_id'], ['video_renders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_videos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('video_render_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('delivered_email_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_linkedin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_render_id'], ['video_renders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach_videos')
    op.drop_table('onboarding_videos')
    with op.batch_alter_table('video_renders', schema=None) as batch_op:
        batch_op.drop_index('idx_video_renders_account_programme_status')

    op.drop_table('video_renders')
    # ### end Alembic commands ###
