"""Add Booking model and booking_duration_minutes

Revision ID: 0352216673b7
Revises: 87e5740df533
Create Date: 2026-04-19 13:38:06.206628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0352216673b7'
down_revision = '87e5740df533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inboxiq_bookings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked_by_name', sa.String(length=255), nullable=True),
    sa.Column('booked_by_email', sa.String(length=255), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('meet_link', sa.String(length=500), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['inboxiq_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inboxiq_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inboxiq_bookings_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('account_feature_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_duration_minutes', sa.Integer(), server_default='30', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_feature_flags', schema=None) as batch_op:
        batch_op.drop_column('booking_duration_minutes')

    with op.batch_alter_table('inboxiq_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inboxiq_bookings_token_hash'))

    op.drop_table('inboxiq_bookings')
    # ### end Alembic commands ###
