"""add job_title to leads + trace_id to agent_events

Revision ID: 03d23258e3c3
Revises: 182c4cc768ff
Create Date: 2026-05-10 17:19:15.234220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d23258e3c3'
down_revision = '182c4cc768ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trace_id', sa.String(length=32), nullable=True, comment='OpenTelemetry trace_id (32-hex) for Phoenix correlation'))
        batch_op.create_index(batch_op.f('ix_agent_events_trace_id'), ['trace_id'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=True, comment="Decision maker role e.g. 'Director of Customer Support'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_events_trace_id'))
        batch_op.drop_column('trace_id')

    # ### end Alembic commands ###
