"""add dynamic_booking_enabled and static_booking_url to account_feature_flags

Revision ID: 03e04f059d8e
Revises: c0343e48e174
Create Date: 2026-05-17 21:05:40.158386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e04f059d8e'
down_revision = 'c0343e48e174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_feature_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dynamic_booking_enabled', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('static_booking_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_feature_flags', schema=None) as batch_op:
        batch_op.drop_column('static_booking_url')
        batch_op.drop_column('dynamic_booking_enabled')

    # ### end Alembic commands ###
