"""empty message

Revision ID: 04803a7d50de
Revises: 905fa2fad69f
Create Date: 2026-02-22 01:41:01.864675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04803a7d50de'
down_revision = '905fa2fad69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_inquiries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_inquiries', schema=None) as batch_op:
        batch_op.create_index('idx_enterprise_inquiries_account', ['account_id'], unique=False)
        batch_op.create_index('idx_enterprise_inquiries_created', ['created_at'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index('ix_automation_studio_waitlist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_studio_waitlist_email')
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('enterprise_inquiries', schema=None) as batch_op:
        batch_op.drop_index('idx_enterprise_inquiries_created')
        batch_op.drop_index('idx_enterprise_inquiries_account')

    op.drop_table('enterprise_inquiries')
    # ### end Alembic commands ###
