"""add passkeys and totp

Revision ID: 0628eb83380a
Revises: 9039cf3dccc9
Create Date: 2025-12-22 14:09:57.095324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0628eb83380a'
down_revision = '9039cf3dccc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passkeys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('credential_id', sa.String(length=512), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', name='uq_passkey_credential')
    )
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passkeys_user_id'), ['user_id'], unique=False)

    op.create_table('totp_devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('totp_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_totp_devices_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('totp_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_totp_devices_user_id'))

    op.drop_table('totp_devices')
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passkeys_user_id'))

    op.drop_table('passkeys')
    # ### end Alembic commands ###
