"""empty message

Revision ID: 08512478fd68
Revises: 9310b6d7b37c
Create Date: 2025-12-30 13:37:11.517768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08512478fd68'
down_revision = '9310b6d7b37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('New Lead', 'Contacted', 'Qualified', 'Closed Won', 'Closed Lost', name='lead_status_enum'), nullable=False),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('qualification_status', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_contact_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_contact_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('sales_agent_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
