"""empty message

Revision ID: 08f1a7fda64b
Revises: 240127ffddcd
Create Date: 2026-03-13 20:48:27.977451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f1a7fda64b'
down_revision = '240127ffddcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kb_articles_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('kb_articles_limit')

    # ### end Alembic commands ###
