"""empty message

Revision ID: 0e7b64def335
Revises: 3590af17ce23
Create Date: 2026-02-07 10:38:55.742500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7b64def335'
down_revision = '3590af17ce23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_studio_waitlist',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('ticket_volume_per_week', sa.Integer(), nullable=True),
    sa.Column('biggest_pain_point', sa.Text(), nullable=True),
    sa.Column('desired_rule_example', sa.Text(), nullable=True),
    sa.Column('pain_score', sa.SmallInteger(), nullable=True),
    sa.Column('opened_email', sa.Boolean(), nullable=False),
    sa.Column('clicked_demo', sa.Boolean(), nullable=False),
    sa.Column('scheduled_interview', sa.Boolean(), nullable=False),
    sa.Column('interview_completed', sa.Boolean(), nullable=False),
    sa.Column('beta_qualified', sa.Boolean(), nullable=False),
    sa.Column('beta_committed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('utm_source', sa.String(length=128), nullable=True),
    sa.Column('utm_campaign', sa.String(length=128), nullable=True),
    sa.Column('utm_medium', sa.String(length=128), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('interview_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beta_committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.create_index('ix_automation_studio_waitlist_beta_qualified', ['beta_qualified'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.drop_index('ix_automation_studio_waitlist_beta_qualified')

    op.drop_table('automation_studio_waitlist')
    # ### end Alembic commands ###
