"""social distribution queue + blog account_id

Revision ID: 182c4cc768ff
Revises: 862256e6aa1a
Create Date: 2026-05-09 18:26:34.110854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182c4cc768ff'
down_revision = '862256e6aa1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_distribution_queue',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('posted_url', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', 'platform', name='uq_sdq_content_platform')
    )
    with op.batch_alter_table('social_distribution_queue', schema=None) as batch_op:
        batch_op.create_index('idx_sdq_account_platform_status_created', ['account_id', 'platform', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blog_posts_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_blog_posts_account_id'))
        batch_op.drop_column('account_id')

    with op.batch_alter_table('social_distribution_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_sdq_account_platform_status_created')

    op.drop_table('social_distribution_queue')
    # ### end Alembic commands ###
