"""add youtube_videos table

Revision ID: 186a8ad11c38
Revises: 5e4a74c40a9f
Create Date: 2026-05-03 18:28:30.105194

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '186a8ad11c38'
down_revision = '5e4a74c40a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_videos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('blog_post_id', sa.String(length=64), nullable=True),
    sa.Column('icp_pain_point_id', sa.String(length=64), nullable=False),
    sa.Column('parent_video_id', sa.String(length=64), nullable=True),
    sa.Column('video_type', sa.String(length=20), nullable=False),
    sa.Column('video_style', sa.String(length=20), server_default='avatar', nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('thumbnail_prompt', sa.Text(), nullable=True),
    sa.Column('illustration_prompts', sa.JSON(), nullable=True),
    sa.Column('dalle_frame_urls', sa.JSON(), nullable=True),
    sa.Column('heygen_job_id', sa.String(length=128), nullable=True),
    sa.Column('heygen_render_url', sa.String(length=512), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=64), nullable=True),
    sa.Column('youtube_url', sa.String(length=256), nullable=True),
    sa.Column('utm_slug', sa.String(length=128), nullable=True),
    sa.Column('utm_source', sa.String(length=64), server_default='youtube', nullable=False),
    sa.Column('utm_medium', sa.String(length=64), nullable=True),
    sa.Column('utm_campaign', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='script_pending', nullable=False),
    sa.Column('script_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('click_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['icp_pain_point_id'], ['icp_pain_points.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_video_id'], ['youtube_videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utm_slug')
    )
    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.create_index('idx_youtube_videos_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index('idx_youtube_videos_published', ['account_id', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.drop_index('idx_youtube_videos_published')
        batch_op.drop_index('idx_youtube_videos_account_status')

    op.drop_table('youtube_videos')
    # ### end Alembic commands ###
