"""Add mfa_setup_required to users

Revision ID: 240127ffddcd
Revises: 88f55f302657
Create Date: 2026-03-12 15:13:15.128517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240127ffddcd'
down_revision = '88f55f302657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_setup_required', sa.Boolean(), server_default='false', nullable=False, comment='True for invited sub-users until they configure TOTP or a passkey'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_setup_required')

    # ### end Alembic commands ###
