"""empty message

Revision ID: 2fc9cecf6491
Revises: 20251213_ticket_assign
Create Date: 2025-12-14 16:03:56.505001

"""
from alembic import op
import sqlalchemy as sa
try:
    import pgvector
    VECTOR_TYPE = pgvector.sqlalchemy.vector.VECTOR(dim=1536)
except Exception:
    VECTOR_TYPE = sa.JSON()


# revision identifiers, used by Alembic.
revision = '2fc9cecf6491'
down_revision = '20251213_ticket_assign'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure pgvector extension exists when using the vector type.
    if VECTOR_TYPE is not sa.JSON():
        op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    op.create_table('ticket_embeddings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('embedding', VECTOR_TYPE, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['inboxiq_tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', name='uq_ticket_embedding_ticket')
    )
    with op.batch_alter_table('ticket_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_embeddings_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_embeddings_ticket_id'))

    op.drop_table('ticket_embeddings')
    # ### end Alembic commands ###
