"""add account_addons table

Revision ID: 30ea0eb212d6
Revises: 2076bd6904cf
Create Date: 2026-05-22 19:00:20.521530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ea0eb212d6'
down_revision = '2076bd6904cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_addons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('addon_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('transactions_this_month', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'addon_type', name='uq_account_addon_type')
    )
    with op.batch_alter_table('account_addons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_addons_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_account_addons_account_type', ['account_id', 'addon_type'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=False)

    with op.batch_alter_table('account_addons', schema=None) as batch_op:
        batch_op.drop_index('ix_account_addons_account_type')
        batch_op.drop_index(batch_op.f('ix_account_addons_account_id'))

    op.drop_table('account_addons')
    # ### end Alembic commands ###
