"""Add account_id to Lead model for future multi-tenancy

Revision ID: 3590af17ce23
Revises: d016e53db12c
Create Date: 2026-02-06 21:18:57.072259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3590af17ce23'
down_revision = 'd016e53db12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True, comment='Multi-tenancy support - default account 2'))
        batch_op.create_index('idx_leads_account_id', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('idx_leads_account_id')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
