"""drop heygen columns from youtube_videos

Revision ID: 364a2807bd6e
Revises: dd8a8ef7424e
Create Date: 2026-05-03 23:56:04.691266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '364a2807bd6e'
down_revision = 'dd8a8ef7424e'
branch_labels = None
depends_on = None


def upgrade():
    # Drop unique constraint and both possible FK names (name varies by how it was created)
    op.execute("ALTER TABLE youtube_videos DROP CONSTRAINT IF EXISTS youtube_videos_heygen_job_id_key")
    op.execute("ALTER TABLE youtube_videos DROP CONSTRAINT IF EXISTS fk_youtube_videos_video_render_id")
    op.execute("ALTER TABLE youtube_videos DROP CONSTRAINT IF EXISTS youtube_videos_video_render_id_fkey")
    # Recreate FK with RESTRICT and make video_render_id NOT NULL
    op.execute("ALTER TABLE youtube_videos ALTER COLUMN video_render_id SET NOT NULL")
    op.execute("ALTER TABLE youtube_videos ADD CONSTRAINT fk_youtube_videos_video_render_id FOREIGN KEY (video_render_id) REFERENCES video_renders(id) ON DELETE RESTRICT")
    # Drop heygen/illustration columns (idempotent)
    op.execute("ALTER TABLE youtube_videos DROP COLUMN IF EXISTS heygen_job_id")
    op.execute("ALTER TABLE youtube_videos DROP COLUMN IF EXISTS illustration_prompts")
    op.execute("ALTER TABLE youtube_videos DROP COLUMN IF EXISTS dalle_frame_urls")
    op.execute("ALTER TABLE youtube_videos DROP COLUMN IF EXISTS heygen_render_url")
    op.execute("ALTER TABLE youtube_videos DROP COLUMN IF EXISTS render_completed_at")
    op.execute("ALTER TABLE youtube_videos DROP COLUMN IF EXISTS render_submitted_at")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('render_submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('render_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('heygen_render_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dalle_frame_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('illustration_prompts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('heygen_job_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('youtube_videos_video_render_id_fkey'), 'video_renders', ['video_render_id'], ['id'], ondelete='SET NULL')
        batch_op.create_unique_constraint(batch_op.f('youtube_videos_heygen_job_id_key'), ['heygen_job_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('video_render_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
