"""Add DraftReplyFeedBack and feature

Revision ID: 373215123885
Revises: 7c3f1b9d3a12
Create Date: 2026-01-31 10:25:58.053687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373215123885'
down_revision = '7c3f1b9d3a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_feature_flags',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('draft_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('draft_reply_auto_approve', sa.Boolean(), nullable=False),
    sa.Column('draft_reply_min_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('draft_reply_feedback',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('edit_distance', sa.Integer(), nullable=True),
    sa.Column('helpfulness_score', sa.SmallInteger(), nullable=True),
    sa.Column('time_saved_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['inboxiq_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_reply_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_draft_reply_feedback_ticket', ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_reply_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_draft_reply_feedback_ticket')

    op.drop_table('draft_reply_feedback')
    op.drop_table('account_feature_flags')
    # ### end Alembic commands ###
