"""add booking_handle to account_feature_flags

Revision ID: 3d4745cbb94c
Revises: 03e04f059d8e
Create Date: 2026-05-17 21:35:58.093520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4745cbb94c'
down_revision = '03e04f059d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_feature_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_handle', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['booking_handle'])

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index('ix_automation_studio_waitlist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_studio_waitlist_email')
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('account_feature_flags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('booking_handle')

    # ### end Alembic commands ###
