"""empty message

Revision ID: 3d68a85b54e9
Revises: 4f0138e03538
Create Date: 2026-02-08 15:19:22.193686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d68a85b54e9'
down_revision = '4f0138e03538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_campaigns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='Multi-tenancy support'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Campaign name (e.g., 'Automation Studio Beta Outreach')"),
    sa.Column('subject_template', sa.String(length=500), nullable=False, comment='Email subject with {{variables}}'),
    sa.Column('body_template', sa.Text(), nullable=False, comment='Email body HTML/text with {{variables}}'),
    sa.Column('from_email', sa.String(length=255), nullable=False, comment='Sender email address'),
    sa.Column('from_name', sa.String(length=255), nullable=True, comment='Sender display name'),
    sa.Column('follow_up_enabled', sa.Boolean(), server_default='true', nullable=True, comment='Enable automated follow-ups'),
    sa.Column('follow_up_delay_days', sa.JSON(), nullable=False, comment='Follow-up delays: [3, 7] for Day 3 and Day 7'),
    sa.Column('target_funnel_stage', sa.String(length=50), nullable=True, comment='Target leads in this stage'),
    sa.Column('target_source', sa.String(length=100), nullable=True, comment='Target leads from this source'),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='campaign_status_enum'), server_default='draft', nullable=False),
    sa.Column('max_recipients', sa.Integer(), nullable=True, comment='Stop after X recipients (e.g., 10 for beta)'),
    sa.Column('total_sent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_opened', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_clicked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_replied', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_email_campaign_status', ['status'], unique=False)

    op.create_table('email_outreaches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('sequence_step', sa.Integer(), server_default='0', nullable=False, comment='0=initial, 1=first follow-up, 2=second follow-up'),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='Rendered subject line'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='Rendered HTML body'),
    sa.Column('body_text', sa.Text(), nullable=False, comment='Rendered plain text body'),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'opened', 'clicked', 'replied', 'bounced', 'failed', name='outreach_status_enum'), server_default='pending', nullable=False),
    sa.Column('ses_message_id', sa.String(length=255), nullable=True, comment='AWS SES Message ID'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('click_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True, comment='When to send next follow-up'),
    sa.Column('followup_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_outreaches', schema=None) as batch_op:
        batch_op.create_index('idx_email_outreach_campaign', ['campaign_id'], unique=False)
        batch_op.create_index('idx_email_outreach_lead', ['lead_id'], unique=False)
        batch_op.create_index('idx_email_outreach_next_followup', ['next_followup_at'], unique=False)
        batch_op.create_index('idx_email_outreach_status', ['status'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=False)

    with op.batch_alter_table('email_outreaches', schema=None) as batch_op:
        batch_op.drop_index('idx_email_outreach_status')
        batch_op.drop_index('idx_email_outreach_next_followup')
        batch_op.drop_index('idx_email_outreach_lead')
        batch_op.drop_index('idx_email_outreach_campaign')

    op.drop_table('email_outreaches')
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_email_campaign_status')

    op.drop_table('email_campaigns')
    # ### end Alembic commands ###
