"""add triage_label_configs

Revision ID: 4b1ff4d69fda
Revises: 08512478fd68
Create Date: 2026-01-23 23:08:46.919075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1ff4d69fda'
down_revision = '08512478fd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_label_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triage_label_configs', schema=None) as batch_op:
        batch_op.create_index('ix_triage_label_configs_account', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_label_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_triage_label_configs_account')

    op.drop_table('triage_label_configs')
    # ### end Alembic commands ###
