"""Hunter domain caching

Revision ID: 55a33538dc45
Revises: 732fb0879e24
Create Date: 2026-02-14 11:10:52.061058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a33538dc45'
down_revision = '732fb0879e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunter_domain_cache',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False, comment='Company domain (e.g., google.com)'),
    sa.Column('emails', sa.JSON(), nullable=True, comment='List of emails found for this domain'),
    sa.Column('email_count', sa.Integer(), nullable=True, comment='Number of emails found'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Cache expiration (30 days)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', name='uq_hunter_domain')
    )
    with op.batch_alter_table('hunter_domain_cache', schema=None) as batch_op:
        batch_op.create_index('idx_hunter_domain_created', ['created_at'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index('ix_automation_studio_waitlist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_studio_waitlist_email')
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('hunter_domain_cache', schema=None) as batch_op:
        batch_op.drop_index('idx_hunter_domain_created')

    op.drop_table('hunter_domain_cache')
    # ### end Alembic commands ###
