"""add auth_events

Revision ID: 58d1981ad20a
Revises: 2fc9cecf6491
Create Date: 2025-12-14 17:45:00.470443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d1981ad20a'
down_revision = '2fc9cecf6491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_events_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_events_email'))
        batch_op.drop_index(batch_op.f('ix_auth_events_account_id'))

    op.drop_table('auth_events')
    # ### end Alembic commands ###
