"""add agent_events

Revision ID: 5a995aaeac17
Revises: 58d1981ad20a
Create Date: 2025-12-14 17:57:45.813830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a995aaeac17'
down_revision = '58d1981ad20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('ticket_id', sa.String(length=64), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.create_index('ix_agent_events_agent_name', ['agent_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_events', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_events_agent_name')

    op.drop_table('agent_events')
    # ### end Alembic commands ###
