"""add icp_pain_points table

Revision ID: 5e4a74c40a9f
Revises: e892d2d3c118
Create Date: 2026-05-03 18:17:26.338433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e4a74c40a9f'
down_revision = 'e892d2d3c118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('icp_pain_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_icp_pain_points_account'))
        batch_op.drop_index(batch_op.f('idx_icp_pain_points_priority'))

    op.drop_table('icp_pain_points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icp_pain_points',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('icp_config_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('pain_point', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('consequence', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('persona', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['icp_config_id'], ['icp_configs.id'], name=op.f('icp_pain_points_icp_config_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('icp_pain_points_pkey'))
    )
    with op.batch_alter_table('icp_pain_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_icp_pain_points_priority'), ['account_id', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_icp_pain_points_account'), ['account_id'], unique=False)

    # ### end Alembic commands ###
