"""Add detailed metrics to DspyTrainingMetric

Revision ID: 5f41493000b5
Revises: 719b7ac29173
Create Date: 2026-02-01 21:25:44.356663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f41493000b5'
down_revision = '719b7ac29173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dspy_training_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('train_weighted', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('eval_weighted', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dspy_training_metrics', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('eval_weighted')
        batch_op.drop_column('train_weighted')
        batch_op.drop_column('seed_count')

    # ### end Alembic commands ###
