"""empty message

Revision ID: 5fcb177ae0df
Revises: a913a1c68927
Create Date: 2025-12-09 21:32:50.636053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcb177ae0df'
down_revision = 'a913a1c68927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_billing_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('billing_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('plan_choice', sa.String(length=32), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_status', sa.String(length=32), nullable=False),
    sa.Column('subscription_status', sa.String(length=32), nullable=False),
    sa.Column('default_payment_method_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_billing_profile_account')
    )
    with op.batch_alter_table('customer_billing_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_billing_profiles_account_id'), ['account_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_payment_method_id', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('last4', sa.String(length=8), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_billing_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_profile_id'), ['profile_id'], unique=False)

    # Add FK after both tables exist to avoid dependency ordering issues
    op.create_foreign_key(
        "fk_billing_profile_default_pm",
        "customer_billing_profiles",
        "payment_methods",
        ["default_payment_method_id"],
        ["id"],
    )

    op.create_table('payment_provider_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('ai_actions', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_billing_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_profile_id'), ['profile_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.String(length=64), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_invoice_id', sa.String(length=128), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['customer_billing_profiles.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_profile_id'), ['profile_id'], unique=False)

    op.create_table('charge_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_payment_intent_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charge_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_attempts_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_billing_profile_default_pm", "customer_billing_profiles", type_="foreignkey")
    with op.batch_alter_table('charge_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_attempts_invoice_id'))

    op.drop_table('charge_attempts')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_profile_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_profile_id'))

    op.drop_table('subscriptions')
    op.drop_table('plans')
    op.drop_table('payment_provider_accounts')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_profile_id'))

    op.drop_table('payment_methods')
    with op.batch_alter_table('customer_billing_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_billing_profiles_account_id'))

    op.drop_table('customer_billing_profiles')
    # ### end Alembic commands ###
