"""Add SenderProfile, ClassificationCorrection, MailboxSyncPreference

Revision ID: 706a5011905d
Revises: a051cb6a0c3c
Create Date: 2026-03-08 18:13:35.610734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706a5011905d'
down_revision = 'a051cb6a0c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_sync_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('canonical_category', sa.String(length=64), nullable=False),
    sa.Column('provider_label', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider', 'canonical_category', name='uq_mailbox_sync_pref')
    )
    with op.batch_alter_table('mailbox_sync_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_mailbox_sync_pref_account', ['account_id'], unique=False)

    op.create_table('sender_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('user_verified', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'domain', name='uq_sender_profile_account_domain')
    )
    with op.batch_alter_table('sender_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_sender_profiles_domain', ['domain'], unique=False)

    op.create_table('classification_corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=True),
    sa.Column('sender_domain', sa.String(length=255), nullable=False),
    sa.Column('original_category', sa.String(length=64), nullable=True),
    sa.Column('corrected_category', sa.String(length=64), nullable=False),
    sa.Column('signal_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['inboxiq_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_corrections', schema=None) as batch_op:
        batch_op.create_index('ix_classification_corrections_account', ['account_id'], unique=False)
        batch_op.create_index('ix_classification_corrections_domain', ['sender_domain'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index('ix_automation_studio_waitlist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_studio_waitlist_email')
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('classification_corrections', schema=None) as batch_op:
        batch_op.drop_index('ix_classification_corrections_domain')
        batch_op.drop_index('ix_classification_corrections_account')

    op.drop_table('classification_corrections')
    with op.batch_alter_table('sender_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_sender_profiles_domain')

    op.drop_table('sender_profiles')
    with op.batch_alter_table('mailbox_sync_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_mailbox_sync_pref_account')

    op.drop_table('mailbox_sync_preferences')
    # ### end Alembic commands ###
