"""Add triage_config table

Revision ID: 719b7ac29173
Revises: eac81afdddac
Create Date: 2026-02-01 15:27:53.627620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719b7ac29173'
down_revision = 'eac81afdddac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('sla_mappings', sa.JSON(), nullable=False),
    sa.Column('sla_hours', sa.JSON(), nullable=False),
    sa.Column('fallback_messages', sa.JSON(), nullable=False),
    sa.Column('default_owner', sa.String(length=128), nullable=True),
    sa.Column('default_team', sa.String(length=128), nullable=True),
    sa.Column('default_category', sa.String(length=64), nullable=True),
    sa.Column('default_priority', sa.String(length=8), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('p2_neutral_auto_handle', sa.Boolean(), nullable=False),
    sa.Column('body_preview_limit', sa.Integer(), nullable=True),
    sa.Column('summary_limit', sa.Integer(), nullable=True),
    sa.Column('train_min_samples', sa.Integer(), nullable=True),
    sa.Column('poll_stale_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_triage_config_account')
    )
    with op.batch_alter_table('triage_configs', schema=None) as batch_op:
        batch_op.create_index('ix_triage_configs_account', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_triage_configs_account')

    op.drop_table('triage_configs')
    # ### end Alembic commands ###
