"""Campaign email senders

Revision ID: 732fb0879e24
Revises: b9ff1f9f53ff
Create Date: 2026-02-14 10:40:19.178836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732fb0879e24'
down_revision = 'b9ff1f9f53ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_senders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='Multi-tenancy'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Sender email (e.g., kofi@kalevent.com)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Display name (e.g., 'Kofi from Kalevent')"),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment='Default sender for new campaigns'),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False, comment='Active sender'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_senders', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_sender_account', ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_senders', schema=None) as batch_op:
        batch_op.drop_index('idx_campaign_sender_account')

    op.drop_table('campaign_senders')
    # ### end Alembic commands ###
