"""Add AutomationRule and AutomationRuleExecution models

Revision ID: 75d0167dd598
Revises: 3d68a85b54e9
Create Date: 2026-02-11 21:12:49.719403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d0167dd598'
down_revision = '3d68a85b54e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('condition_logic', sa.String(length=16), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('stop_on_error', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_category', sa.String(length=64), nullable=True),
    sa.Column('cloned_from_template_id', sa.String(length=64), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_execution_time_ms', sa.Float(), nullable=True),
    sa.Column('estimated_time_saved_hours', sa.Float(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.create_index('ix_automation_rules_account_enabled', ['account_id', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_enabled'), ['enabled'], unique=False)

    op.create_table('automation_rule_executions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=True),
    sa.Column('lead_id', sa.String(length=64), nullable=True),
    sa.Column('trigger_event', sa.String(length=64), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_context', sa.JSON(), nullable=True),
    sa.Column('conditions_evaluated', sa.JSON(), nullable=True),
    sa.Column('actions_executed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['inboxiq_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rule_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rule_executions_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_automation_rule_executions_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_automation_rule_executions_rule_id', ['rule_id'], unique=False)
        batch_op.create_index('ix_automation_rule_executions_ticket_id', ['ticket_id'], unique=False)
        batch_op.create_index('ix_automation_rule_executions_trace_id', ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_rule_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_rule_executions_trace_id')
        batch_op.drop_index('ix_automation_rule_executions_ticket_id')
        batch_op.drop_index('ix_automation_rule_executions_rule_id')
        batch_op.drop_index('ix_automation_rule_executions_created_at')
        batch_op.drop_index(batch_op.f('ix_automation_rule_executions_account_id'))

    op.drop_table('automation_rule_executions')
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_rules_enabled'))
        batch_op.drop_index(batch_op.f('ix_automation_rules_account_id'))
        batch_op.drop_index('ix_automation_rules_account_enabled')

    op.drop_table('automation_rules')
    # ### end Alembic commands ###
