"""Add MarketingSpend

Revision ID: 78a35215a15d
Revises: f3965fd29518
Create Date: 2026-02-21 12:18:01.257745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a35215a15d'
down_revision = 'f3965fd29518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_spend',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('amount_gbp', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketing_spend', schema=None) as batch_op:
        batch_op.create_index('idx_marketing_spend_period', ['period'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=False)

    with op.batch_alter_table('marketing_spend', schema=None) as batch_op:
        batch_op.drop_index('idx_marketing_spend_period')

    op.drop_table('marketing_spend')
    # ### end Alembic commands ###
