"""empty message

Revision ID: 7b03c59566e6
Revises: 0628eb83380a
Create Date: 2025-12-22 19:29:34.979680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b03c59566e6'
down_revision = '0628eb83380a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_draft',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_title', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('brief_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rendered_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('whitepaper_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('brief_json', sa.JSON(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('markdown', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rendered_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brief_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_prompt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('last_prompt')
        batch_op.drop_column('brief_json')
        batch_op.drop_column('rendered_html')
        batch_op.drop_column('markdown')

    op.drop_table('whitepaper_drafts')
    op.drop_table('newsletter_draft')
    # ### end Alembic commands ###
