"""Add webhook provider and automation suggestion

Revision ID: 7d7201ccf301
Revises: 75d0167dd598
Create Date: 2026-02-12 18:45:36.408597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7201ccf301'
down_revision = '75d0167dd598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_providers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('configuration_name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=True),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('webhook_signing_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('destination_provider_id', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('failed_requests', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['destination_provider_id'], ['webhook_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_providers_account_id'), ['account_id'], unique=False)

    op.create_table('automation_suggestions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('plain_english', sa.Text(), nullable=False),
    sa.Column('workflow_json', sa.JSON(), nullable=False),
    sa.Column('estimated_time_saved_per_week', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_savings_per_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sample_ticket_ids', sa.JSON(), nullable=True),
    sa.Column('pattern_occurrences', sa.Integer(), nullable=True),
    sa.Column('total_analyzed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_rule_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery_method', sa.String(length=64), nullable=True),
    sa.Column('lookback_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_rule_id'], ['automation_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_suggestions_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_suggestions_account_id'))

    op.drop_table('automation_suggestions')
    with op.batch_alter_table('webhook_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_providers_account_id'))

    op.drop_table('webhook_providers')
    # ### end Alembic commands ###
