"""Lead: add job_title + country

Revision ID: 81e1740722db
Revises: db54a53b2e71
Create Date: 2026-05-08 18:34:46.091927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e1740722db'
down_revision = 'db54a53b2e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=True))
        batch_op.create_index('idx_leads_country', ['country'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('idx_leads_country')
        batch_op.drop_column('country')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
