"""empty message

Revision ID: 87e5740df533
Revises: c0257a1bd9d2
Create Date: 2026-04-06 10:50:54.375499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e5740df533'
down_revision = 'c0257a1bd9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('condition_logic', sa.String(length=16), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_policies', schema=None) as batch_op:
        batch_op.create_index('ix_approval_policies_account_enabled', ['account_id', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_policies_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index('ix_automation_studio_waitlist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_studio_waitlist_email')
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('approval_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_policies_account_id'))
        batch_op.drop_index('ix_approval_policies_account_enabled')

    op.drop_table('approval_policies')
    # ### end Alembic commands ###
