"""empty message

Revision ID: 9039cf3dccc9
Revises: d98bc3fd2ac2
Create Date: 2025-12-20 19:43:48.038355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9039cf3dccc9'
down_revision = 'd98bc3fd2ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('allowed_ips', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_tokens', schema=None) as batch_op:
        batch_op.drop_column('allowed_ips')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
