"""Expand Plan quotas and feature flags, add AccountUsageCounter

Revision ID: 905fa2fad69f
Revises: 78a35215a15d
Create Date: 2026-02-22 00:27:21.839689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905fa2fad69f'
down_revision = '78a35215a15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_usage_counters',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('ai_decisions', sa.Integer(), nullable=False),
    sa.Column('chat_conversations', sa.Integer(), nullable=False),
    sa.Column('automation_runs', sa.Integer(), nullable=False),
    sa.Column('content_posts', sa.Integer(), nullable=False),
    sa.Column('leads_discovered', sa.Integer(), nullable=False),
    sa.Column('nurture_emails', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'billing_month')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('automation_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('content_gen_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('lead_discovery_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('nurture_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('distribution_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('api_access_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('registered_apps_limit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ai_decisions_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chat_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('automation_runs_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_posts_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('leads_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nurture_emails_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stripe_ai_overage_price_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('stripe_chat_overage_price_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('stripe_automation_overage_price_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('stripe_leads_overage_price_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('stripe_nurture_overage_price_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('stripe_nurture_overage_price_id')
        batch_op.drop_column('stripe_leads_overage_price_id')
        batch_op.drop_column('stripe_automation_overage_price_id')
        batch_op.drop_column('stripe_chat_overage_price_id')
        batch_op.drop_column('stripe_ai_overage_price_id')
        batch_op.drop_column('nurture_emails_limit')
        batch_op.drop_column('leads_limit')
        batch_op.drop_column('content_posts_limit')
        batch_op.drop_column('automation_runs_limit')
        batch_op.drop_column('chat_limit')
        batch_op.drop_column('ai_decisions_limit')
        batch_op.drop_column('registered_apps_limit')
        batch_op.drop_column('api_access_enabled')
        batch_op.drop_column('distribution_enabled')
        batch_op.drop_column('nurture_enabled')
        batch_op.drop_column('lead_discovery_enabled')
        batch_op.drop_column('content_gen_enabled')
        batch_op.drop_column('automation_enabled')
        batch_op.drop_column('chat_enabled')

    op.drop_table('account_usage_counters')
    # ### end Alembic commands ###
