"""Generate leads table

Revision ID: 9310b6d7b37c
Revises: 7b03c59566e6
Create Date: 2025-12-30 13:28:28.806668

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '9310b6d7b37c'
down_revision = '7b03c59566e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_draft', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('whitepaper_drafts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitepaper_drafts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('newsletter_draft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
