"""add aria_conversations table

Revision ID: 9b4a09c7f1ab
Revises: ee5bc0fbc385
Create Date: 2026-05-23 22:01:57.677298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4a09c7f1ab'
down_revision = 'ee5bc0fbc385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aria_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('visitor_name', sa.String(length=200), nullable=False),
    sa.Column('visitor_email', sa.String(length=200), nullable=False),
    sa.Column('branch', sa.String(length=20), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aria_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aria_conversations_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index('ix_automation_studio_waitlist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_studio_waitlist_email')
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('aria_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aria_conversations_account_id'))

    op.drop_table('aria_conversations')
    # ### end Alembic commands ###
