"""Add llm cost tracking columns to inboxiq_tickets

Revision ID: a051cb6a0c3c
Revises: cb99e615cc12
Create Date: 2026-03-06 19:56:50.272905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a051cb6a0c3c'
down_revision = 'cb99e615cc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxiq_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('llm_tokens_in', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('llm_tokens_out', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('llm_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxiq_tickets', schema=None) as batch_op:
        batch_op.drop_column('llm_cost_usd')
        batch_op.drop_column('llm_tokens_out')
        batch_op.drop_column('llm_tokens_in')
        batch_op.drop_column('llm_model')

    # ### end Alembic commands ###
