"""Add NurtureEmailSend for nurture dedup and AB testing

Revision ID: a12377425759
Revises: 99d008562870
Create Date: 2026-02-21 10:21:45.345606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12377425759'
down_revision = '99d008562870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurture_email_sends',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False, comment='discovery | consideration'),
    sa.Column('sequence_day', sa.Integer(), nullable=False, comment='1, 3, 7, 14, or 21'),
    sa.Column('ab_variant', sa.String(length=1), nullable=True, comment='A or B'),
    sa.Column('subject_line', sa.String(length=500), nullable=True, comment='Actual subject sent — for comparing variants'),
    sa.Column('vertical', sa.String(length=50), nullable=True, comment='b2b_saas or ecommerce'),
    sa.Column('opened', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('clicked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'campaign_type', 'sequence_day', name='uq_nurture_send')
    )
    with op.batch_alter_table('nurture_email_sends', schema=None) as batch_op:
        batch_op.create_index('idx_nurture_ab', ['campaign_type', 'ab_variant', 'sequence_day'], unique=False)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index('ix_automation_studio_waitlist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_studio_waitlist_email')
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('nurture_email_sends', schema=None) as batch_op:
        batch_op.drop_index('idx_nurture_ab')

    op.drop_table('nurture_email_sends')
    # ### end Alembic commands ###
