"""empty message

Revision ID: a7c46fa7e998
Revises: a44c9bea48a9
Create Date: 2026-02-23 20:41:39.037483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c46fa7e998'
down_revision = 'a44c9bea48a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_usage_counters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incoming_signals', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_usage_counters', schema=None) as batch_op:
        batch_op.drop_column('incoming_signals')

    # ### end Alembic commands ###
