"""add outreach_video_enabled to email_campaigns and subject_line to video_renders

Revision ID: b6570669bcb2
Revises: a45d78ca1e2f
Create Date: 2026-05-04 02:51:14.275789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6570669bcb2'
down_revision = 'a45d78ca1e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outreach_video_enabled', sa.Boolean(), server_default='false', nullable=False, comment='Enable personalised outreach video for qualifying leads'))

    with op.batch_alter_table('video_renders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_line', sa.String(length=255), nullable=True, comment='DSPy-generated email subject (outreach programme)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_renders', schema=None) as batch_op:
        batch_op.drop_column('subject_line')

    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.drop_column('outreach_video_enabled')

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=False)

    # ### end Alembic commands ###
