"""Add ROI tracking fields to AutomationRule and AutomationRuleExecution

Revision ID: b9ff1f9f53ff
Revises: 7d7201ccf301
Create Date: 2026-02-12 18:54:27.043527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ff1f9f53ff'
down_revision = '7d7201ccf301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_rule_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_reassigned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reassignment_timestamp', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline_time_per_execution', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('baseline_cost_per_execution', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_time_saved_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_cost_saved', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('accuracy_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_executions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('successful_executions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('suggestion_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'automation_suggestions', ['suggestion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('suggestion_id')
        batch_op.drop_column('source')
        batch_op.drop_column('successful_executions')
        batch_op.drop_column('total_executions')
        batch_op.drop_column('accuracy_rate')
        batch_op.drop_column('total_cost_saved')
        batch_op.drop_column('total_time_saved_seconds')
        batch_op.drop_column('baseline_cost_per_execution')
        batch_op.drop_column('baseline_time_per_execution')

    with op.batch_alter_table('automation_rule_executions', schema=None) as batch_op:
        batch_op.drop_column('reassignment_timestamp')
        batch_op.drop_column('ticket_reassigned')

    # ### end Alembic commands ###
