"""Add AccountLLMConfig model to src/models/core.py + permitted registry

Revision ID: be7e1669ffd9
Revises: d19d69c9a9ea
Create Date: 2026-03-05 13:15:10.012311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7e1669ffd9'
down_revision = 'd19d69c9a9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_llm_configs',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='openai | anthropic | ollama | openai_compatible'),
    sa.Column('base_url', sa.String(length=512), nullable=True, comment='Required for ollama/openai_compatible, fixed for openai/anthropic'),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=True, comment="Fernet-encrypted API key; null for providers that don't need one (local ollama)"),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_llm_configs')
    # ### end Alembic commands ###
