"""Add distributed_at to blog_posts

Revision ID: c0257a1bd9d2
Revises: f46dfdcb29fa
Create Date: 2026-03-25 20:47:51.904993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0257a1bd9d2'
down_revision = 'f46dfdcb29fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True, comment='Set when distribution tasks are queued'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('distributed_at')

    # ### end Alembic commands ###
