"""add registered_app_id to tickets, add app_webhook_deliveries

Revision ID: c0343e48e174
Revises: b517c78d1f64
Create Date: 2026-05-15 16:13:21.373585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0343e48e174'
down_revision = 'b517c78d1f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_webhook_deliveries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('app_id', sa.String(length=64), nullable=False),
    sa.Column('product_slug', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['registered_apps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('inboxiq_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_app_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'registered_apps', ['registered_app_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxiq_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('registered_app_id')

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=False)

    op.drop_table('app_webhook_deliveries')
    # ### end Alembic commands ###
