"""add video_render_id fk to youtube_videos

Revision ID: c1f907d5dd34
Revises: 014d3d636535
Create Date: 2026-05-03 21:31:11.521214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f907d5dd34'
down_revision = '014d3d636535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_render_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('fk_youtube_videos_video_render_id', 'video_renders', ['video_render_id'], ['id'], ondelete='SET NULL')

    op.create_index('idx_youtube_videos_video_render_id', 'youtube_videos', ['video_render_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_youtube_videos_video_render_id', table_name='youtube_videos')

    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_youtube_videos_video_render_id', type_='foreignkey')
        batch_op.drop_column('video_render_id')

    # ### end Alembic commands ###
