"""multi-inbox: swap unique constraint, add display_name

Revision ID: c5d0bca27a75
Revises: 706a5011905d
Create Date: 2026-03-10 15:42:52.253681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d0bca27a75'
down_revision = '706a5011905d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_provider_inbox'), type_='unique')
        batch_op.create_unique_constraint('uq_account_email_inbox', ['account_id', 'email_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_connections', schema=None) as batch_op:
        batch_op.drop_constraint('uq_account_email_inbox', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_provider_inbox'), ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
