"""Add provider_message_id and provider_thread_id to tickets

Revision ID: cb99e615cc12
Revises: 7ea9c6847546
Create Date: 2026-03-06 17:26:14.907453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb99e615cc12'
down_revision = '7ea9c6847546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('inboxiq_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_message_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider_thread_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxiq_tickets', schema=None) as batch_op:
        batch_op.drop_column('provider_thread_id')
        batch_op.drop_column('provider_message_id')

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=False)

    # ### end Alembic commands ###
