"""inbox invite token fields

Revision ID: cdeea9104799
Revises: c5d0bca27a75
Create Date: 2026-03-10 16:32:26.346077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdeea9104799'
down_revision = 'c5d0bca27a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_token', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('invite_token_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_connections', schema=None) as batch_op:
        batch_op.drop_column('invite_token_expires_at')
        batch_op.drop_column('invite_token')

    # ### end Alembic commands ###
