"""empty message

Revision ID: ce126edcbd61
Revises: 20251212_merge_heads
Create Date: 2025-12-13 12:04:18.568870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce126edcbd61'
down_revision = '20251212_merge_heads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('funnel_stage', sa.String(length=16), nullable=True),
    sa.Column('primary_keyword', sa.String(length=255), nullable=True),
    sa.Column('secondary_keywords', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(length=512), nullable=True),
    sa.Column('hero_image_url', sa.String(length=1024), nullable=True),
    sa.Column('hero_image_alt', sa.String(length=255), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('read_time_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('internal_links', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_blog_slug')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=False)

    with op.batch_alter_table('inboxiq_testimonials', schema=None) as batch_op:
        batch_op.drop_index('ix_inboxiq_testimonials_account')
        batch_op.drop_index('ix_inboxiq_testimonials_user')
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('inboxiq_tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_inboxiq_tickets_search_vec')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxiq_tickets', schema=None) as batch_op:
        batch_op.create_index('ix_inboxiq_tickets_search_vec', ['search_vec'], unique=False)

    with op.batch_alter_table('inboxiq_testimonials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_inboxiq_testimonials_user', ['user_id'], unique=False)
        batch_op.create_index('ix_inboxiq_testimonials_account', ['account_id'], unique=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))

    op.drop_table('blog_posts')
    # ### end Alembic commands ###
