"""empty message

Revision ID: d016e53db12c
Revises: f97689139ef6
Create Date: 2026-02-06 16:35:10.857532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd016e53db12c'
down_revision = 'f97689139ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitched_blog_topics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Working title or topic idea'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description or angle'),
    sa.Column('target_keyword', sa.String(length=255), nullable=True, comment='Primary keyword to target'),
    sa.Column('secondary_keywords', sa.JSON(), nullable=False, comment='Additional keywords'),
    sa.Column('funnel_stage', sa.String(length=50), nullable=True, comment='discovery | consideration | decision'),
    sa.Column('target_audience', sa.String(length=500), nullable=True, comment='Target audience/persona'),
    sa.Column('niche', sa.String(length=255), nullable=True, comment='Blog niche (e.g., Revenue Operations)'),
    sa.Column('pitch_notes', sa.Text(), nullable=True, comment='Additional notes from submitter'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending | approved | rejected | generated'),
    sa.Column('priority', sa.SmallInteger(), nullable=False, comment='1=high, 2=medium, 3=low'),
    sa.Column('submitted_by', sa.String(length=255), nullable=True, comment='Email of submitter'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_content_id', sa.String(length=64), nullable=True, comment='Link to generated content if used'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_content_id'], ['generated_content.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pitched_blog_topics', schema=None) as batch_op:
        batch_op.create_index('idx_pitched_topics_created', ['created_at'], unique=False)
        batch_op.create_index('idx_pitched_topics_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitched_blog_topics', schema=None) as batch_op:
        batch_op.drop_index('idx_pitched_topics_status')
        batch_op.drop_index('idx_pitched_topics_created')

    op.drop_table('pitched_blog_topics')
    # ### end Alembic commands ###
