"""add unique constraint to heygen_job_id, add fk indexes to child video tables

Revision ID: dd8a8ef7424e
Revises: c1f907d5dd34
Create Date: 2026-05-03 21:46:35.554001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8a8ef7424e'
down_revision = 'c1f907d5dd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_videos', schema=None) as batch_op:
        batch_op.create_index('idx_onboarding_videos_account_video_render', ['account_id', 'video_render_id'], unique=False)

    with op.batch_alter_table('outreach_videos', schema=None) as batch_op:
        batch_op.create_index('idx_outreach_videos_account_video_render', ['account_id', 'video_render_id'], unique=False)

    with op.batch_alter_table('video_renders', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['heygen_job_id'])

    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.create_index('idx_youtube_videos_video_render_id', ['video_render_id'], unique=False)
        batch_op.create_unique_constraint(None, ['heygen_job_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_youtube_videos_video_render_id')

    with op.batch_alter_table('video_renders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('outreach_videos', schema=None) as batch_op:
        batch_op.drop_index('idx_outreach_videos_account_video_render')

    with op.batch_alter_table('onboarding_videos', schema=None) as batch_op:
        batch_op.drop_index('idx_onboarding_videos_account_video_render')

    # ### end Alembic commands ###
