"""Add LinkedInProspect, ICPConfig, Lead.linkedin_url

Revision ID: de741d7100b5
Revises: 0352216673b7
Create Date: 2026-04-27 22:34:04.807827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de741d7100b5'
down_revision = '0352216673b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icp_configs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('titles', sa.JSON(), nullable=False),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.Column('company_size_min', sa.Integer(), nullable=False),
    sa.Column('company_size_max', sa.Integer(), nullable=False),
    sa.Column('geographies', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_linkedin_url'), ['linkedin_url'], unique=False)

    with op.batch_alter_table('linkedin_prospects', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'blog_posts', ['suggested_post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linkedin_prospects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_linkedin_url'))
        batch_op.drop_column('linkedin_url')

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=False)

    op.drop_table('icp_configs')
    # ### end Alembic commands ###
