"""add newsletter_opt_in to users

Revision ID: e892d2d3c118
Revises: de741d7100b5
Create Date: 2026-04-28 23:27:32.543395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e892d2d3c118'
down_revision = 'de741d7100b5'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS newsletter_opt_in "
        "BOOLEAN NOT NULL DEFAULT true"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('newsletter_opt_in')

    # ### end Alembic commands ###
