"""Add knowledge base Integration model

Revision ID: eac81afdddac
Revises: 373215123885
Create Date: 2026-01-31 16:40:12.773582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac81afdddac'
down_revision = '373215123885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_integrations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_integrations_account_id'), ['account_id'], unique=False)

    op.create_table('kb_articles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('integration_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('external_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['kb_integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.create_index('ix_kb_articles_external_id', ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_articles_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index('ix_kb_articles_integration_title', ['integration_id', 'title'], unique=False)

    op.create_table('kb_article_embeddings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('article_id', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['kb_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_article_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_article_embeddings_article_id'), ['article_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_article_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_article_embeddings_article_id'))

    op.drop_table('kb_article_embeddings')
    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.drop_index('ix_kb_articles_integration_title')
        batch_op.drop_index(batch_op.f('ix_kb_articles_integration_id'))
        batch_op.drop_index('ix_kb_articles_external_id')

    op.drop_table('kb_articles')
    with op.batch_alter_table('kb_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_integrations_account_id'))

    op.drop_table('kb_integrations')
    # ### end Alembic commands ###
