"""add banner_dismissed_at to onboarding_videos

Revision ID: eddf8f518f20
Revises: 364a2807bd6e
Create Date: 2026-05-04 01:35:15.022441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddf8f518f20'
down_revision = '364a2807bd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_dismissed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_videos', schema=None) as batch_op:
        batch_op.drop_column('banner_dismissed_at')

    # ### end Alembic commands ###
