"""add aria_book_demo_enabled to account_feature_flags

Revision ID: ee5bc0fbc385
Revises: 30ea0eb212d6
Create Date: 2026-05-23 12:09:08.844344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5bc0fbc385'
down_revision = '30ea0eb212d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_feature_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aria_book_demo_enabled', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_feature_flags', schema=None) as batch_op:
        batch_op.drop_column('aria_book_demo_enabled')

    # ### end Alembic commands ###
