"""Add User.role

Revision ID: f1cd58f6217d
Revises: 3165adc0ebd8
Create Date: 2026-03-04 17:23:01.075785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cd58f6217d'
down_revision = '3165adc0ebd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), server_default='agent', nullable=False, comment='owner | admin | agent | viewer | billing'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
