"""Add referral_source to accounts

Revision ID: f2845dd9f2d4
Revises: 08f1a7fda64b
Create Date: 2026-03-18 19:14:39.763239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2845dd9f2d4'
down_revision = '08f1a7fda64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_source', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('referral_source')

    # ### end Alembic commands ###
