"""empty message

Revision ID: f31bb9ef6217
Revises: a12377425759
Create Date: 2026-02-21 11:20:33.006221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31bb9ef6217'
down_revision = 'a12377425759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_app_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('target_account_id', sa.Integer(), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('referrer_lead_id', sa.String(length=64), nullable=True),
    sa.Column('referrer_email', sa.String(length=255), nullable=False),
    sa.Column('referred_email', sa.String(length=255), nullable=True),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_page', sa.String(length=255), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index('idx_referral_account', ['account_id'], unique=False)
        batch_op.create_index('idx_referral_code', ['referral_code'], unique=True)

    op.create_table('in_app_message_dismissals',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['in_app_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=False)

    op.drop_table('in_app_message_dismissals')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index('idx_referral_code')
        batch_op.drop_index('idx_referral_account')

    op.drop_table('referrals')
    op.drop_table('in_app_messages')
    # ### end Alembic commands ###
