"""Add Landing page

Revision ID: f3965fd29518
Revises: f31bb9ef6217
Create Date: 2026-02-21 11:56:21.046177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3965fd29518'
down_revision = 'f31bb9ef6217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_pages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('subheadline', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=False),
    sa.Column('cta_color', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('lead_count', sa.Integer(), nullable=False),
    sa.Column('utm_source', sa.String(length=200), nullable=True),
    sa.Column('utm_campaign', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landing_pages', schema=None) as batch_op:
        batch_op.create_index('idx_landing_page_account', ['account_id'], unique=False)
        batch_op.create_index('idx_landing_page_slug', ['slug'], unique=True)

    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_studio_waitlist_email'))
        batch_op.create_index('ix_automation_studio_waitlist_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation_studio_waitlist', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_studio_waitlist_email')
        batch_op.create_index(batch_op.f('ix_automation_studio_waitlist_email'), ['email'], unique=True)

    with op.batch_alter_table('landing_pages', schema=None) as batch_op:
        batch_op.drop_index('idx_landing_page_slug')
        batch_op.drop_index('idx_landing_page_account')

    op.drop_table('landing_pages')
    # ### end Alembic commands ###
