"""Add outreach_unsubscribed_at to leads, unsubscribe_token and unsubscribed status to email_outreaches

Revision ID: f46dfdcb29fa
Revises: f2845dd9f2d4
Create Date: 2026-03-23 11:44:14.716777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46dfdcb29fa'
down_revision = 'f2845dd9f2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_outreaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubscribe_token', sa.String(length=64), nullable=True, comment='Token embedded in unsubscribe link — one per outreach record'))
        batch_op.create_index(batch_op.f('ix_email_outreaches_unsubscribe_token'), ['unsubscribe_token'], unique=True)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outreach_unsubscribed_at', sa.DateTime(timezone=True), nullable=True, comment='Set when lead opts out of outreach emails'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('outreach_unsubscribed_at')

    with op.batch_alter_table('email_outreaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_outreaches_unsubscribe_token'))
        batch_op.drop_column('unsubscribe_token')

    # ### end Alembic commands ###
