"""add plan enforcement columns

Revision ID: f7a6cbfa5e36
Revises: 3d4745cbb94c
Create Date: 2026-05-21 21:23:56.402797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a6cbfa5e36'
down_revision = '3d4745cbb94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('byol_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('audit_log_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('kb_drafts_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('inbox_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('automation_rules_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('automation_rules_limit')
        batch_op.drop_column('inbox_limit')
        batch_op.drop_column('kb_drafts_enabled')
        batch_op.drop_column('audit_log_enabled')
        batch_op.drop_column('byol_enabled')

    # ### end Alembic commands ###
