"""empty message

Revision ID: f97689139ef6
Revises: 5f41493000b5
Create Date: 2026-02-04 19:41:54.167873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97689139ef6'
down_revision = '5f41493000b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnel_metrics_daily',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('entries', sa.Integer(), server_default='0', nullable=True),
    sa.Column('exits', sa.Integer(), server_default='0', nullable=True),
    sa.Column('conversions_to_next', sa.Integer(), server_default='0', nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('avg_time_in_stage_hours', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='if cost tracking enabled'),
    sa.Column('cost_per_entry', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', 'stage', 'source', 'campaign', name='uq_funnel_metrics_date_stage_source_campaign')
    )
    with op.batch_alter_table('funnel_metrics_daily', schema=None) as batch_op:
        batch_op.create_index('idx_funnel_metrics_date', ['metric_date', 'stage'], unique=False)

    op.create_table('generated_content',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment='blog_post | email | case_study | landing_page | social_post'),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True, comment='{meta_title, meta_description, target_keywords, seo_score, word_count}'),
    sa.Column('generation_pipeline', sa.JSON(), nullable=True, comment='{topic_module_output, outline_module_output, writer_output, editor_output, seo_output}'),
    sa.Column('dspy_version', sa.String(length=50), nullable=True, comment='Track which DSPy model version generated this'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='Human feedback: 0-10'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=True, comment='draft | published | archived'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('funnel_stage', sa.String(length=50), nullable=True, comment='Which funnel stage this content supports'),
    sa.Column('target_audience', sa.JSON(), nullable=True, comment='ICP characteristics'),
    sa.Column('performance_metrics', sa.JSON(), nullable=True, comment='{views, engagement_rate, conversions, seo_ranking}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.create_index('idx_generated_content_funnel_stage', ['funnel_stage'], unique=False)
        batch_op.create_index('idx_generated_content_published', ['published_at'], unique=False, postgresql_where=sa.text('published_at IS NOT NULL'))
        batch_op.create_index('idx_generated_content_type', ['content_type', 'status'], unique=False)

    op.create_table('lead_attribution',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('touchpoint_order', sa.Integer(), nullable=False, comment='1st, 2nd, 3rd... touch'),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('campaign', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('term', sa.String(length=255), nullable=True),
    sa.Column('attribution_model', sa.String(length=50), server_default='first_touch', nullable=True, comment='first_touch, last_touch, linear, time_decay'),
    sa.Column('attribution_weight', sa.Float(), server_default='1.0', nullable=True),
    sa.Column('touched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_attribution', schema=None) as batch_op:
        batch_op.create_index('idx_attribution_lead', ['lead_id', 'touchpoint_order'], unique=False)

    op.create_table('lead_engagement_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='email_open, page_visit, content_download, etc.'),
    sa.Column('event_source', sa.String(length=100), nullable=True, comment='email_campaign, website, linkedin, etc.'),
    sa.Column('event_data', sa.JSON(), nullable=True, comment='URL visited, campaign ID, etc.'),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_engagement_events', schema=None) as batch_op:
        batch_op.create_index('idx_engagement_lead', ['lead_id', 'created_at'], unique=False)
        batch_op.create_index('idx_engagement_type', ['event_type', 'created_at'], unique=False)

    op.create_table('lead_funnel_stages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False, comment='visits | discovery | consideration | conversion | retention'),
    sa.Column('sub_stage', sa.String(length=100), nullable=True, comment='e.g. demo_requested, trial_active, onboarding'),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversion_probability', sa.Float(), nullable=True, comment='DSPy prediction at entry'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Stage-specific data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_funnel_stages', schema=None) as batch_op:
        batch_op.create_index('idx_funnel_stage', ['stage', 'entered_at'], unique=False)
        batch_op.create_index('idx_funnel_stage_lead', ['lead_id'], unique=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_content_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('auto_generated', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('dspy_quality_score', sa.Float(), nullable=True))
        batch_op.create_index('idx_blog_posts_generated', ['generated_content_id'], unique=False)
        batch_op.create_foreign_key(None, 'generated_content', ['generated_content_id'], ['id'])

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_funnel_stage', sa.String(length=50), server_default='visits', nullable=True, comment='visits | discovery | consideration | conversion | retention'))
        batch_op.add_column(sa.Column('stage_entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('fit_score', sa.Integer(), server_default='0', nullable=True, comment='ICP fit 0-10'))
        batch_op.add_column(sa.Column('intent_score', sa.Integer(), server_default='0', nullable=True, comment='Buying intent 0-12'))
        batch_op.add_column(sa.Column('conversion_probability', sa.Float(), nullable=True, comment='DSPy prediction'))
        batch_op.add_column(sa.Column('last_engagement_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('engagement_count', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('first_attribution_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('first_attribution_campaign', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_size_bucket', sa.String(length=50), nullable=True, comment='50-100, 101-300, 301-500'))
        batch_op.add_column(sa.Column('buying_committee', sa.JSON(), nullable=True, comment='[{name, title, email, role}]'))
        batch_op.add_column(sa.Column('objections', sa.JSON(), nullable=True, comment='DSPy-detected objections'))
        batch_op.add_column(sa.Column('recommended_assets', sa.JSON(), nullable=True, comment='DSPy recommendations'))
        batch_op.create_index('idx_leads_fit_intent', ['fit_score', 'intent_score'], unique=False)
        batch_op.create_index('idx_leads_funnel_stage', ['current_funnel_stage', 'stage_entered_at'], unique=False)
        batch_op.create_index('idx_leads_last_engagement', ['last_engagement_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('idx_leads_last_engagement')
        batch_op.drop_index('idx_leads_funnel_stage')
        batch_op.drop_index('idx_leads_fit_intent')
        batch_op.drop_column('recommended_assets')
        batch_op.drop_column('objections')
        batch_op.drop_column('buying_committee')
        batch_op.drop_column('company_size_bucket')
        batch_op.drop_column('first_attribution_campaign')
        batch_op.drop_column('first_attribution_source')
        batch_op.drop_column('engagement_count')
        batch_op.drop_column('last_engagement_at')
        batch_op.drop_column('conversion_probability')
        batch_op.drop_column('intent_score')
        batch_op.drop_column('fit_score')
        batch_op.drop_column('stage_entered_at')
        batch_op.drop_column('current_funnel_stage')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_blog_posts_generated')
        batch_op.drop_column('dspy_quality_score')
        batch_op.drop_column('auto_generated')
        batch_op.drop_column('generated_content_id')

    with op.batch_alter_table('lead_funnel_stages', schema=None) as batch_op:
        batch_op.drop_index('idx_funnel_stage_lead')
        batch_op.drop_index('idx_funnel_stage')

    op.drop_table('lead_funnel_stages')
    with op.batch_alter_table('lead_engagement_events', schema=None) as batch_op:
        batch_op.drop_index('idx_engagement_type')
        batch_op.drop_index('idx_engagement_lead')

    op.drop_table('lead_engagement_events')
    with op.batch_alter_table('lead_attribution', schema=None) as batch_op:
        batch_op.drop_index('idx_attribution_lead')

    op.drop_table('lead_attribution')
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.drop_index('idx_generated_content_type')
        batch_op.drop_index('idx_generated_content_published', postgresql_where=sa.text('published_at IS NOT NULL'))
        batch_op.drop_index('idx_generated_content_funnel_stage')

    op.drop_table('generated_content')
    with op.batch_alter_table('funnel_metrics_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_funnel_metrics_date')

    op.drop_table('funnel_metrics_daily')
    # ### end Alembic commands ###
