apiVersion: apps/v1
kind: Deployment
metadata:
  name: inboxiq
  namespace: kaley
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inboxiq
  template:
    metadata:
      labels:
        app: inboxiq
    spec:
      containers:
        - name: inboxiq
          image: 094985084741.dkr.ecr.us-west-2.amazonaws.com/inboxiq:${TAG_VALUE}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "production"
          envFrom:
            - secretRef:
                name: inboxiq-env
            - configMapRef:
                name: inboxiq-config
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
