import os
import pytest

os.environ.setdefault("APP_ENV", "test")

from src.app import create_app


@pytest.fixture
def app():
    app = create_app()
    app.config["TESTING"] = True
    app.config["SECRET_KEY"] = "test-secret"
    return app


def test_send_outreach_video_email_returns_false_when_smtp_not_configured(app):
    with app.app_context():
        app.config.pop("SMTP_HOST", None)
        from src.notifications.emails import send_outreach_video_email
        result = send_outreach_video_email(
            to_email="ceo@acme.com",
            recipient_name="James Brown",
            video_url="https://cdn.heygen.com/outreach.mp4",
            subject="James, spotted something about Acme",
        )
        assert result is False


def test_send_outreach_video_email_uses_dspy_subject(app):
    """Subject must come from the `subject` parameter, not be generated by the function."""
    from unittest.mock import patch, MagicMock

    with app.app_context():
        app.config["SMTP_HOST"] = "smtp.example.com"
        app.config["SMTP_PORT"] = 587
        app.config["SMTP_USER"] = "u"
        app.config["SMTP_PASSWORD"] = "p"
        app.config["SMTP_USE_TLS"] = True
        app.config["SMTP_USE_SSL"] = False

        captured = {}

        def fake_send(msg):
            captured["subject"] = msg["Subject"]

        with patch("smtplib.SMTP") as mock_smtp:
            mock_server = MagicMock()
            mock_smtp.return_value.__enter__ = lambda s: mock_server
            mock_smtp.return_value.__exit__ = MagicMock(return_value=False)
            mock_server.send_message.side_effect = fake_send

            from src.notifications.emails import send_outreach_video_email
            result = send_outreach_video_email(
                to_email="ceo@acme.com",
                recipient_name="James Brown",
                video_url="https://cdn.heygen.com/outreach.mp4",
                subject="James, spotted something about Acme",
            )

        assert result is True
        assert captured["subject"] == "James, spotted something about Acme"


def test_send_outreach_video_email_html_escapes_name_and_url(app):
    """XSS guard: name and video URL must be HTML-escaped in the body."""
    from unittest.mock import patch, MagicMock

    with app.app_context():
        app.config["SMTP_HOST"] = "smtp.example.com"
        app.config["SMTP_PORT"] = 587
        app.config["SMTP_USER"] = "u"
        app.config["SMTP_PASSWORD"] = "p"
        app.config["SMTP_USE_TLS"] = True
        app.config["SMTP_USE_SSL"] = False

        captured = {}

        def fake_send(msg):
            captured["html"] = msg.get_payload(decode=False)

        with patch("smtplib.SMTP") as mock_smtp:
            mock_server = MagicMock()
            mock_smtp.return_value.__enter__ = lambda s: mock_server
            mock_smtp.return_value.__exit__ = MagicMock(return_value=False)
            mock_server.send_message.side_effect = fake_send

            from src.notifications.emails import send_outreach_video_email
            send_outreach_video_email(
                to_email="ceo@acme.com",
                recipient_name='<script>alert("xss")</script>',
                video_url="https://cdn.heygen.com/outreach.mp4",
                subject="Test",
            )

        msg_str = str(captured.get("html", ""))
        assert "<script>" not in msg_str


def test_send_outreach_video_email_returns_false_on_smtp_error(app):
    from unittest.mock import patch, MagicMock

    with app.app_context():
        app.config["SMTP_HOST"] = "smtp.example.com"
        app.config["SMTP_PORT"] = 587
        app.config["SMTP_USER"] = "u"
        app.config["SMTP_PASSWORD"] = "p"
        app.config["SMTP_USE_TLS"] = True
        app.config["SMTP_USE_SSL"] = False

        with patch("smtplib.SMTP") as mock_smtp:
            mock_server = MagicMock()
            mock_smtp.return_value.__enter__ = lambda s: mock_server
            mock_smtp.return_value.__exit__ = MagicMock(return_value=False)
            mock_server.send_message.side_effect = Exception("Connection refused")

            from src.notifications.emails import send_outreach_video_email
            result = send_outreach_video_email(
                to_email="ceo@acme.com",
                recipient_name="James Brown",
                video_url="https://cdn.heygen.com/outreach.mp4",
                subject="James, spotted something about Acme",
            )

        assert result is False
