from datetime import datetime
from uuid import uuid4
from sqlalchemy.sql import func
from sqlalchemy.dialects.postgresql import TSVECTOR
from src.extensions import db

try:  # Optional pgvector support
    from pgvector.sqlalchemy import Vector  # type: ignore
except Exception:
    Vector = None

class Referral(db.Model):
    """
    Tracks referral links generated by leads/users.

    Flow: generate code → share link → visitor clicks (status=clicked) →
    visitor signs up / submits intake → status=converted.

    referrer_lead_id is nullable so future signed-up users can also generate codes.
    """
    __tablename__ = "referrals"
    __table_args__ = (
        db.Index("idx_referral_code", "referral_code", unique=True),
        db.Index("idx_referral_account", "account_id"),
    )

    id = db.Column(db.String(64), primary_key=True, default=lambda: str(uuid4()), nullable=False)
    account_id = db.Column(db.Integer, db.ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False)
    referrer_lead_id = db.Column(db.String(64), db.ForeignKey("leads.id", ondelete="SET NULL"), nullable=True)
    referrer_email = db.Column(db.String(255), nullable=False)
    referred_email = db.Column(db.String(255), nullable=True)       # Set on conversion
    referral_code = db.Column(db.String(32), nullable=False)        # URL-safe, unique
    status = db.Column(db.String(20), nullable=False, default="pending")  # pending|clicked|converted|rewarded
    source_page = db.Column(db.String(255), nullable=True)          # Which page the share came from
    ip_hash = db.Column(db.String(64), nullable=True)               # SHA256 of visitor IP for dedup
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())
    clicked_at = db.Column(db.DateTime(timezone=True), nullable=True)
    converted_at = db.Column(db.DateTime(timezone=True), nullable=True)


class InAppMessage(db.Model):
    """
    Admin-created broadcast messages shown as banners in the dashboard.

    target controls who sees the message:
      "all"   — every logged-in user
      "trial" — only users whose account is on a trial plan
      "paid"  — only users on a paid plan

    target_account_id narrows to a single account (overrides target if set).
    published_at = NULL means the message is a draft (not yet shown).
    expires_at = NULL means it never auto-expires.
    """
    __tablename__ = "in_app_messages"

    id = db.Column(db.String(64), primary_key=True, default=lambda: str(uuid4()), nullable=False)
    title = db.Column(db.String(200), nullable=False)
    body = db.Column(db.Text, nullable=False)
    type = db.Column(db.String(20), nullable=False, default="info")     # info | success | warning
    target = db.Column(db.String(20), nullable=False, default="all")    # all | trial | paid
    target_account_id = db.Column(db.Integer, nullable=True)            # NULL = all matching accounts
    cta_text = db.Column(db.String(100), nullable=True)
    cta_url = db.Column(db.String(500), nullable=True)
    published_at = db.Column(db.DateTime(timezone=True), nullable=True) # NULL = draft
    expires_at = db.Column(db.DateTime(timezone=True), nullable=True)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())


class InAppMessageDismissal(db.Model):
    """
    Tracks which users have dismissed which in-app messages.
    Composite PK prevents duplicate dismissal rows.
    """
    __tablename__ = "in_app_message_dismissals"

    message_id = db.Column(db.String(64), db.ForeignKey("in_app_messages.id", ondelete="CASCADE"),
                           primary_key=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="CASCADE"),
                        primary_key=True, nullable=False)
    dismissed_at = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())


class LandingPage(db.Model):
    """
    Admin-created campaign landing pages served at /lp/<slug>.

    Each page captures leads via a public form — name, email, optional company.
    UTM params from the query string are stored on the Lead and LeadAttribution records
    created on form submit, enabling end-to-end paid ad attribution.

    status:
      "draft"     — not publicly visible (404 on GET /lp/<slug>)
      "published" — live; view_count and lead_count incremented automatically
      "archived"  — removed from public view, data retained
    """
    __tablename__ = "landing_pages"
    __table_args__ = (
        db.Index("idx_landing_page_slug", "slug", unique=True),
        db.Index("idx_landing_page_account", "account_id"),
    )

    id = db.Column(db.String(64), primary_key=True, default=lambda: str(uuid4()), nullable=False)
    account_id = db.Column(db.Integer, db.ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False)

    # Content
    title = db.Column(db.String(200), nullable=False)                    # internal admin label
    slug = db.Column(db.String(200), nullable=False)                     # URL slug → /lp/<slug>
    headline = db.Column(db.String(300), nullable=False)                 # hero headline
    subheadline = db.Column(db.String(500), nullable=True)
    body_html = db.Column(db.Text, nullable=True)                        # sanitized rich body

    # CTA config
    cta_text = db.Column(db.String(100), nullable=False, default="Get Started")
    cta_color = db.Column(db.String(20), nullable=False, default="indigo")  # indigo|emerald|amber|rose

    # Publishing
    status = db.Column(db.String(20), nullable=False, default="draft")   # draft|published|archived
    published_at = db.Column(db.DateTime(timezone=True), nullable=True)

    # Analytics counters (best-effort; no locking required)
    view_count = db.Column(db.Integer, nullable=False, default=0)
    lead_count = db.Column(db.Integer, nullable=False, default=0)

    # Optional UTM annotation for admin reference only (not pre-filled in form)
    utm_source = db.Column(db.String(200), nullable=True)
    utm_campaign = db.Column(db.String(200), nullable=True)

    created_at = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at = db.Column(db.DateTime(timezone=True), nullable=False,
                           server_default=func.now(), onupdate=func.now())


class MarketingSpend(db.Model):
    """
    Manual ad spend entries for CAC calculation.

    Admin enters monthly spend per channel (Google, LinkedIn, etc.).
    CAC = total_spend_period / new_customers_period.
    period is stored as "YYYY-MM" strings for easy grouping.
    """
    __tablename__ = "marketing_spend"
    __table_args__ = (
        db.Index("idx_marketing_spend_period", "period"),
    )

    id = db.Column(db.String(64), primary_key=True, default=lambda: str(uuid4()), nullable=False)
    period = db.Column(db.String(7), nullable=False)                     # "2026-02"
    channel = db.Column(db.String(100), nullable=False)                  # google|linkedin|twitter|other
    amount_gbp = db.Column(db.Float, nullable=False)
    notes = db.Column(db.String(500), nullable=True)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())


class EnterpriseInquiry(db.Model):
    """
    Enterprise plan inquiries submitted via the in-app form or public page.

    Stores enough context for the sales team to follow up, plus the account_id
    of the submitter if they are already a logged-in user.
    """
    __tablename__ = "enterprise_inquiries"
    __table_args__ = (
        db.Index("idx_enterprise_inquiries_account", "account_id"),
        db.Index("idx_enterprise_inquiries_created", "created_at"),
    )

    id = db.Column(db.String(64), primary_key=True, default=lambda: str(uuid4()), nullable=False)
    # Submitter details
    name = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(255), nullable=False)
    company = db.Column(db.String(200), nullable=True)
    phone = db.Column(db.String(50), nullable=True)
    employee_count = db.Column(db.Integer, nullable=True)       # rough org size
    message = db.Column(db.Text, nullable=True)                 # free-text from user
    # Link to account if already signed in
    account_id = db.Column(db.Integer, db.ForeignKey("accounts.id", ondelete="SET NULL"), nullable=True)
    # Status tracking
    status = db.Column(db.String(30), nullable=False, default="new")  # new | contacted | closed
    admin_notes = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at = db.Column(db.DateTime(timezone=True), onupdate=func.now())


class ICPConfig(db.Model):
    """Per-account ICP criteria used by the LinkedIn discovery task."""
    __tablename__ = "icp_configs"

    id = db.Column(db.String(64), primary_key=True, default=lambda: str(uuid4()))
    account_id = db.Column(db.Integer, nullable=False, unique=True)
    titles = db.Column(
        db.JSON,
        nullable=False,
        default=lambda: ["Founder", "Head of Support", "Operations Lead", "Customer Success Lead"],
    )
    industries = db.Column(db.JSON, nullable=False, default=lambda: ["B2B SaaS", "Software"])
    company_size_min = db.Column(db.Integer, nullable=False, default=10)
    company_size_max = db.Column(db.Integer, nullable=False, default=50)
    geographies = db.Column(db.JSON, nullable=False, default=lambda: ["UK", "US", "Nigeria"])
    created_at = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())
