import smtplib
from email.message import EmailMessage
from typing import Optional

from flask import current_app


def send_content_review_email(
    to_email: str,
    title: str,
    slug: str,
    content_preview: str,
    seo_score: str,
    word_count: int,
    readability_score: str,
    blog_url: str
) -> bool:
    """Send content review email with generated blog post details."""
    app = current_app
    host = app.config.get("SMTP_HOST")
    port = app.config.get("SMTP_PORT")
    user = app.config.get("SMTP_USER")
    password = app.config.get("SMTP_PASSWORD")
    use_tls = app.config.get("SMTP_USE_TLS", True)
    use_ssl = app.config.get("SMTP_USE_SSL", False)
    mail_from = app.config.get("MAIL_FROM", "noreply@kalevent.com")

    if not host:
        app.logger.info({
            "event": "email.disabled",
            "reason": "SMTP_HOST not configured",
            "to": to_email
        })
        return False

    # Truncate content preview
    preview = content_preview[:500] + "..." if len(content_preview) > 500 else content_preview

    msg = EmailMessage()
    msg["Subject"] = f"📝 New Blog Post Published: {title}"
    msg["From"] = mail_from
    msg["To"] = to_email
    msg.set_content(
        f"""
Hi,

A new blog post has been auto-published by the Content Generation Agent:

Title: {title}
URL: {blog_url}
Word Count: {word_count}
SEO Score: {seo_score}/100
Readability: {readability_score}/100

Content Preview:
{preview}

Review the full post and suggest improvements by replying to this email.

Thanks,
Content Generation Agent
        """.strip()
    )
    msg.add_alternative(
        f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #4F46E5;">📝 New Blog Post Published</h2>

            <p>A new blog post has been auto-published by the Content Generation Agent:</p>

            <div style="background: #F3F4F6; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h3 style="margin-top: 0; color: #111827;">{title}</h3>

                <div style="margin: 15px 0;">
                    <strong>URL:</strong> <a href="{blog_url}" style="color: #4F46E5;">{blog_url}</a>
                </div>

                <div style="display: flex; gap: 20px; margin: 15px 0;">
                    <div><strong>Word Count:</strong> {word_count}</div>
                    <div><strong>SEO Score:</strong> {seo_score}/100</div>
                    <div><strong>Readability:</strong> {readability_score}/100</div>
                </div>
            </div>

            <div style="background: #FFFBEB; border-left: 4px solid #F59E0B; padding: 15px; margin: 20px 0;">
                <h4 style="margin-top: 0; color: #92400E;">Content Preview</h4>
                <p style="color: #78350F; white-space: pre-wrap;">{preview}</p>
            </div>

            <p>
                <a href="{blog_url}"
                   style="display: inline-block; background: #4F46E5; color: white; padding: 12px 24px;
                          text-decoration: none; border-radius: 6px; margin-top: 10px;">
                    View Full Post →
                </a>
            </p>

            <p style="color: #6B7280; font-size: 14px; margin-top: 30px;">
                <strong>Suggest Improvements:</strong> Reply to this email with your feedback and I'll optimize the content accordingly.
            </p>

            <hr style="border: none; border-top: 1px solid #E5E7EB; margin: 30px 0;">

            <p style="color: #9CA3AF; font-size: 12px;">
                Generated by Content Generation Agent (DSPy-powered)<br>
                Funnel v2.0 | InboxIQ
            </p>
        </div>
        """,
        subtype="html"
    )

    try:
        if use_ssl:
            with smtplib.SMTP_SSL(host, port) as server:
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(host, port) as server:
                if use_tls:
                    server.starttls()
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        return True
    except Exception as exc:
        app.logger.exception("Failed to send content review email: %s", exc)
        return False


def send_activation_email(to_email: str, activation_link: str, account_name: str) -> bool:
    """Send activation email. Returns True on success, False otherwise."""
    app = current_app
    host = app.config.get("SMTP_HOST")
    port = app.config.get("SMTP_PORT")
    user = app.config.get("SMTP_USER")
    password = app.config.get("SMTP_PASSWORD")
    use_tls = app.config.get("SMTP_USE_TLS", True)
    use_ssl = app.config.get("SMTP_USE_SSL", False)
    mail_from = app.config.get("MAIL_FROM", "noreply@kalevent.com")

    if not host:
        app.logger.info(
            {
                "event": "email.disabled",
                "reason": "SMTP_HOST not configured",
                "to": to_email,
                "activation_link": activation_link,
            }
        )
        return False

    msg = EmailMessage()
    msg["Subject"] = "Activate your InboxIQ account"
    msg["From"] = mail_from
    msg["To"] = to_email
    msg.set_content(
        f"Hi,\n\nWelcome to InboxIQ! Activate your account for {account_name}:\n{activation_link}\n\nThanks,\nThe Kalevent Team"
    )
    msg.add_alternative(
        f"""
        <p>Hi,</p>
        <p>Welcome to InboxIQ! You're 60 seconds away from having an AI agent triage your emails automatically.</p>
        <p><strong>Activate your account:</strong> <a href="{activation_link}">Activate Your Account →</a></p>
        <p>Thanks,<br/>The Kalevent Team</p>
        """,
        subtype="html",
    )

    try:
        if use_ssl:
            with smtplib.SMTP_SSL(host, port) as server:
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(host, port) as server:
                if use_tls:
                    server.starttls()
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        app.logger.info({"event": "email.sent", "to": to_email})
        return True
    except Exception as exc:  # pragma: no cover - defensive
        app.logger.warning({"event": "email.failed", "to": to_email, "error": str(exc)})
        return False


def send_password_reset_email(to_email: str, reset_link: str, account_id: int | None = None) -> bool:
    """Send password reset email (optionally including workspace/account id)."""
    app = current_app
    host = app.config.get("SMTP_HOST")
    port = app.config.get("SMTP_PORT")
    user = app.config.get("SMTP_USER")
    password = app.config.get("SMTP_PASSWORD")
    use_tls = app.config.get("SMTP_USE_TLS", True)
    use_ssl = app.config.get("SMTP_USE_SSL", False)
    mail_from = app.config.get("MAIL_FROM", "noreply@kalevent.com")

    if not host:
        app.logger.info({"event": "email.disabled", "reason": "SMTP_HOST not configured", "to": to_email})
        return False

    msg = EmailMessage()
    msg["Subject"] = "Reset your InboxIQ password"
    msg["From"] = mail_from
    msg["To"] = to_email
    workspace_line = f"Workspace ID: {account_id}\n" if account_id is not None else ""
    workspace_html = f"<p><strong>Workspace ID:</strong> {account_id}</p>" if account_id is not None else ""

    msg.set_content(
        "Hi,\n\nWe received a request to reset your InboxIQ password.\n"
        f"{workspace_line}"
        f"Reset your password: {reset_link}\n\n"
        "If you didn't request this, you can ignore this email.\n\nThanks,\nThe Kalevent Team"
    )
    msg.add_alternative(
        f"""
        <p>Hi,</p>
        <p>We received a request to reset your InboxIQ password.</p>
        {workspace_html}
        <p><strong>Reset your password:</strong> <a href="{reset_link}">Reset Password →</a></p>
        <p>If you didn't request this, you can ignore this email.</p>
        <p>Thanks,<br/>The Kalevent Team</p>
        """,
        subtype="html",
    )

    try:
        if use_ssl:
            with smtplib.SMTP_SSL(host, port) as server:
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(host, port) as server:
                if use_tls:
                    server.starttls()
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        app.logger.info({"event": "email.sent.reset", "to": to_email})
        return True
    except Exception as exc:  # pragma: no cover - defensive
        app.logger.warning({"event": "email.failed.reset", "to": to_email, "error": str(exc)})
        return False


def send_test_email(to_email: str) -> bool:
    """Send a simple test email to validate delivery. Returns True on success."""
    app = current_app
    host = app.config.get("SMTP_HOST")
    port = app.config.get("SMTP_PORT")
    user = app.config.get("SMTP_USER")
    password = app.config.get("SMTP_PASSWORD")
    use_tls = app.config.get("SMTP_USE_TLS", True)
    use_ssl = app.config.get("SMTP_USE_SSL", False)
    mail_from = app.config.get("MAIL_FROM", "noreply@kalevent.com")

    if not host:
        app.logger.info({"event": "email.disabled", "reason": "SMTP_HOST not configured", "to": to_email})
        return False

    msg = EmailMessage()
    msg["Subject"] = "InboxIQ test email"
    msg["From"] = mail_from
    msg["To"] = to_email
    msg.set_content(
        "Hi,\n\nThis is a test email from InboxIQ to validate your delivery pipeline. "
        "If you received this, your agent can ingest and triage emails.\n\nThanks,\nThe Kalevent Team"
    )
    msg.add_alternative(
        """
        <p>Hi,</p>
        <p>This is a test email from <strong>InboxIQ</strong> to validate your delivery pipeline.</p>
        <p>If you received this, your agent can ingest and triage emails.</p>
        <p>Thanks,<br/>The Kalevent Team</p>
        """,
        subtype="html",
    )

    try:
        if use_ssl:
            with smtplib.SMTP_SSL(host, port) as server:
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(host, port) as server:
                if use_tls:
                    server.starttls()
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        app.logger.info({"event": "email.sent.test", "to": to_email})
        return True
    except Exception as exc:  # pragma: no cover - defensive
        app.logger.warning({"event": "email.failed.test", "to": to_email, "error": str(exc)})
        return False


def send_onboarding_reminder(to_email: str, stage: int) -> bool:
    """Send staged onboarding reminder emails (stage 1/2/3). Returns True on success."""
    app = current_app
    host = app.config.get("SMTP_HOST")
    port = app.config.get("SMTP_PORT")
    user = app.config.get("SMTP_USER")
    password = app.config.get("SMTP_PASSWORD")
    use_tls = app.config.get("SMTP_USE_TLS", True)
    use_ssl = app.config.get("SMTP_USE_SSL", False)
    mail_from = app.config.get("MAIL_FROM", "noreply@kalevent.com")

    if not host:
        app.logger.info({"event": "email.disabled", "reason": "SMTP_HOST not configured", "to": to_email})
        return False

    stage_templates = {
        1: {
          "subject": "Ready to see your AI agent triage its first email?",
          "body": (
              "You’re almost done! Connect your inbox to activate automatic triage.\n\n"
              "Connect Inbox →"
          ),
          "body_html": (
              "<p>You’re almost done! Connect your inbox to activate automatic triage.</p>"
              "<p><strong>Connect Inbox →</strong></p>"
          ),
        },
        2: {
          "subject": "Your AI Support Agent is waiting to be activated",
          "body": (
              "InboxIQ is most powerful once connected to your email.\n\n"
              "With one click, you’ll unlock:\n"
              "✓ Automatic ticket creation\n"
              "✓ Priority + sentiment detection\n"
              "✓ Faster response times\n\n"
              "Activate your agent now →"
          ),
          "body_html": (
              "<p>InboxIQ is most powerful once connected to your email.</p>"
              "<p>With one click, you’ll unlock:</p>"
              "<ul>"
              "<li>Automatic ticket creation</li>"
              "<li>Priority + sentiment detection</li>"
              "<li>Faster response times</li>"
              "</ul>"
              "<p><strong>Activate your agent now →</strong></p>"
          ),
        },
        3: {
          "subject": "Still drowning in support emails? Let’s finish setup.",
          "body": (
              "InboxIQ can eliminate 80% of your triage workload.\n\n"
              "Want help setting it up? Book a free 10-minute onboarding call.\n\n"
              "Book Onboarding →"
          ),
          "body_html": (
              "<p>InboxIQ can eliminate 80% of your triage workload.</p>"
              "<p>Want help setting it up? Book a free 10-minute onboarding call.</p>"
              "<p><strong>Book Onboarding →</strong></p>"
          ),
        },
    }

    template = stage_templates.get(stage)
    if not template:
        app.logger.warning({"event": "email.reminder.skipped", "to": to_email, "reason": f"invalid stage {stage}"})
        return False

    msg = EmailMessage()
    msg["Subject"] = template["subject"]
    msg["From"] = mail_from
    msg["To"] = to_email
    msg.set_content(template["body"])
    msg.add_alternative(template["body_html"], subtype="html")

    try:
        if use_ssl:
            with smtplib.SMTP_SSL(host, port) as server:
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(host, port) as server:
                if use_tls:
                    server.starttls()
                if user and password:
                    server.login(user, password)
                server.send_message(msg)
        app.logger.info({"event": "email.sent.reminder", "to": to_email, "stage": stage})
        return True
    except Exception as exc:  # pragma: no cover - defensive
        app.logger.warning({"event": "email.failed.reminder", "to": to_email, "stage": stage, "error": str(exc)})
        return False
